### PR TITLE
Added ie10 support for flexbox

### PR DESCRIPTION
**Pull request by magsout**

### CODE REVIEW

**Comment by bloodyowl** [comment]
this doesn't seem correct given http://zomigi.com/blog/flexbox-syntax-for-ie-10/

**Comment by magsout** [comment]
My bad, a bit too fast. I send the good properties.

**Comment by magsout** [comment]
OK, this is fixed. I used autoprefixer

**Comment by bloodyowl** [comment]
I meant

``` javascript
  const alignItemsOldValues = {
    "flex-start": "start",
    "flex-end": "end",
    "center": "center",
    "baseline": "baseline",
    "stretch": "stretch",
  }

  if (style.hasOwnProperty("alignItems")) {
    Object.assign(style, {
      WebkitAlignItems: style.alignItems,
      msAlign: alignItemsOldValues[style.alignItems],
    })
  }
```

and

``` javascript
  const justifyContentOldValues = {
    "flex-start": "start",
    "flex-end": "end",
    "space-between": "justify",
    "space-around": "distribute",
  }

  if (style.hasOwnProperty("justifyContent")) {
    Object.assign(style, {
      WebkitJustifyContent: style.justifyContent,
      msFlexPack: justifyContentOldValues[style.justifyContent],
    })
  }
```

should make it work, or has it been fixed in IE10?

**Comment by magsout** [comment]
@bloodyowl ah yes you're right too. Fixed in ie11, but not in ie10

**Comment by magsout** [comment]
Just updated with your proposal and the sources:
- your last comment
- https://msdn.microsoft.com/library/dn265027%28v=vs.85%29.aspx
- https://f.cloud.github.com/assets/284476/516126/49b8cd6e-be9c-11e2-964d-253a303f8f7b.png

what do you prefer about `const` ? top of file ? or just before the property ?

Hope, it's good now.. Sorry for your wasted time

**Pull request closed without merging**
